### ISSUE TITLE
Delete indices create by geonames track

### ISSUE THREAD

**Issue by aclowkey** [elastic/rally-tracks#106]
I think the indices create by the test should be deleted.

**Comment by danielmitterdorfer** [comment]
The indices are deleted at the beginning of the benchmark but - intentionally - not at the end because you might want to inspect its contents. We also assume that a dedicated cluster is used for benchmarking that is completely wiped after an investigation is over. In all other cases, benchmarks might be prone to issues like ordering bias.

**Comment by aclowkey** [comment]
In our situation we run **rally** on a periodic schedule and never inspect. 
So I think it would be good to provide a parameter such as 'clean-after-test' or something similar.

I mean it's not hard to just `curl`, maybe this is the workaround.
I opened the issue because I thought it might be a common situation

P.S. We are testing it on production environment

**Comment by danielmitterdorfer** [comment]
We strongly discourage such a setup because your benchmark environment is not in a well-defined state when you don't start from scratch.

Also, testing in production (probably) means that you have additional load on your cluster that can skew your measurement results even further.

Please see our blog post [Seven Tips for Better Elasticsearch Benchmarks](https://www.elastic.co/blog/seven-tips-for-better-elasticsearch-benchmarks) for more tips about benchmarking methodology.

**Comment by aclowkey** [comment]
Thanks for quick response!

**Comment by danielmitterdorfer** [comment]
You're welcome. :)
