### ISSUE TITLE
Tracks should only wait for green for the indices they care about

### ISSUE THREAD

**Issue by dakrone** [elastic/rally-tracks#37]
When running tracks like `nested`, it waits for the entire cluster to be green, rather than waiting for only the `sonested` index to be green. The track operations should ignore the other (potentially non-allocated) indices on the node.

**Comment by danielmitterdorfer** [comment]
That is currently more of a Rally issue, because it is Rally that waits for the cluster to become green rather than the track. However, Rally is currently moving into this direction:

* The [--cluster-health parameter is deprecated](https://github.com/elastic/rally/issues/364) with 0.8.0 (next release at the time of this writing)
* With Rally 0.9.0 we will switch from implicit index management (check health + delete / create index) to [explicit index management](https://github.com/elastic/rally/issues/293), which means that it is really the responsibility of the track to define the cluster health operation. 

I'll link this as a related ticket in the Rally repo, so we won't forget this in the migration.

**Comment by danielmitterdorfer** [comment]
Relates https://github.com/elastic/rally/issues/380 where we will remove support for automatic index management. When we adjust our standard tracks to do explicit index management, we just need to specify an index / index pattern in the cluster health operation.
