### ISSUE TITLE
Allow to use the "update" action in update challenges

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally-tracks#49]
Our "update" challenges simulate id conflicts but use the "index" action. We should parameterize the action so we can also use the "update" action which allows us to benchmark scenarios like https://github.com/elastic/elasticsearch/issues/26802 in our nightly benchmarks.

**Comment by jmeagher** [comment]
Adding a specific use case we use ElasticSearch for the searching capability instead of trying that with our database layer. The indexing workload ends up being about 90% updates and 10% indexes. All operations are done via the `/_bulk` endpoint. 

A typical index vs update flow would look like:

* Index to create the initial document with 50-100 fields
* Update 3-4 fields or nested documents on a daily to weekly basis

**Comment by danielmitterdorfer** [comment]
Thanks for the use case. To me this sounds as if this should be solved with a dedicated corpus that includes documents and the corresponding action-and-meta-data line though because the documents that should be updated need to be crafted specifically. The approach we use here instead is to simulate id conflicts randomly (but based on a configurable probability) and then emit either an `index` or `update` action in the corresponding meta-data line but we always use the full document. Hope that makes sense now with my additional explanation.
