### ISSUE TITLE
can you add new tracks config for old distribution-version for compare same race config with different elasticserach version

### ISSUE THREAD

**Issue by k3v8ns** [elastic/rally-tracks#70]
can you add new tracks config for old distribution-version for compare same race config with different elasticserach version.

i want to comapre same track races for different elasticsearch version ,but some new add track config not exists in old branch .

could you help to do this ?? or let me know the reason.

**Comment by danielmitterdorfer** [comment]
Hi @k3v8ns and thanks for your interest in Rally! Some of our tracks do not make sense for older versions because they test features that are only available in newer versions or sometimes it does not make much sense backporting (see e.g. https://github.com/elastic/rally-tracks/pull/62#issuecomment-462467134).

I'm closing this issue as there is no action item at the moment for us but we're always open for pull requests. :)

**Comment by k3v8ns** [comment]
even though old version is not suitable with track config, is there any new v7 track is suitable for v6x

**Comment by danielmitterdorfer** [comment]
@k3v8ns I am not sure what you are asking for exactly? Can you please elaborate?

**Comment by k3v8ns** [comment]
rally-track have many branchs for different distrubution-version, and ES v7.0Beta is just releaseed weeks ago, master branch is more suitable for V7.

as you said , same track have no sense for different ES version. but in my oppinion, v6.6+ and v7 compare testing result is meaning.

**Comment by danielmitterdorfer** [comment]
I do agree with you that it is important to be able to compare across Elasticsearch versions, after all that is one of the main points of our benchmarks. Thus the vast majority of the tracks are actually available down to version 1.0 of Elasticsearch so I wonder what *specific* track you're missing?

> how can i modify master branch config for testing V6.6+ release??

You need to cherry-pick the respective commits from the `master` branch to the branch `6`. Then you need to run the benchmarks with a compatible version of Elasticsearch (e.g. 6.6.2) and fix any problems that come up. After that you can create a pull request and we can discuss integration of the backported track to version 6. But as I said in my original comment: We do backport all tracks by default as far as we can unless there is a specific reason *not* to do it (usually because that feature is missing in Elasticsearch).
