### ISSUE TITLE
http_logs add force merge to 1 segment (#90) 

### ISSUE THREAD

**Issue by kailasgoliwadekar** [elastic/rally-tracks#91]
Hi,

Can anyone please comment if the force merge works correctly as its takes  close to 8000 seconds for this operation ? 

The entire http_logs track gets executed in 12,200 seconds from 3400 earlier.  Few times I ran this and can get 5700 seconds .

My Index median throughput is about 298,000 docs/second

Thanks
Kailas

**Comment by danielmitterdorfer** [comment]
Thank you very much for your interest in Rally.

Since this is a user question, and we'd like to direct these kinds of things to the [Rally forum](https://discuss.elastic.co/c/elasticsearch/rally). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests and allow other users to benefit from the discussion in the forum.

As such, I hope you don't mind that I close this.

Just as a hint: force-merges are known to be I/O intensive and this is a several GB index. How long it takes depends also on the type of disk you are using. If you are interested in running only a subset of the operations you can use [`--include-tasks`](https://esrally.readthedocs.io/en/stable/command_line_reference.html#include-tasks). Please use Discuss for any follow-up questions.
